"use client";

import { useState } from "react";

import { MomentumGlyph } from "./momentum-glyph";

import styles from "./momo-avatar.module.css";

export type MomoAvatarAgent = {
  name: string;
  display_name?: string | null;
  description?: string;
};

export type MomoSizeBucket = "sm" | "md" | "lg";

/**
 * Roster `agent.name` -> shipped Momo slug (public/momentum/momos/<slug>.svg).
 * Only names with a confident fit are mapped here. Everything else falls
 * through to MomentumGlyph.
 *
 * Two rosters feed this: the fleet definitions in fleet/agents/*\/config.yaml
 * and the managed subagents the Command Center lists from /api/subagents
 * (dillon-* and momentum-*). "lead" is not a roster name: the Command Center
 * seeds the lead card with it, whichever agent is leading. dillon-client-
 * operations, dillon-revenue and dillon-growth have no artwork yet and keep
 * the glyph on purpose.
 */
const SLUG_MAP: Record<string, string> = {
  "analytics-engineer": "analytics",
  "data-migration-engineer": "migration",
  "independent-verifier": "verifier",
  "fleet-scout": "research",
  "fleet-builder": "builder",
  "fleet-qa": "qa",
  "fleet-reliability": "reliability",
  "senior-software-engineer": "engineer",
  lead: "lead",
  "dillon-builder": "builder",
  "dillon-critic": "qa",
  "dillon-reliability": "reliability",
  "dillon-intelligence": "research",
  "momentum-independent-verifier": "verifier",
  "momentum-analytics-engineer": "analytics",
  "momentum-solutions-architect": "engineer",
  "momentum-migration-engineer": "migration",
};

// ponytail: manual manifest instead of a build-time fs glob of momos/. Every
// slug here must have a matching public/momentum/momos/<slug>.svg, generated by
// scripts/generate-momos.mjs — a slug listed without its file would fire a 404
// before onError fell back to the glyph. Add a fs-glob manifest only if this
// list grows unwieldy to hand-maintain.
const AVAILABLE_MOMO_SLUGS: ReadonlySet<string> = new Set([
  "analytics",
  "builder",
  "engineer",
  "lead",
  "migration",
  "qa",
  "reliability",
  "research",
  "verifier",
]);

function slugFor(name: string): string | null {
  const bare = name.replace(/^dillon-/, "");
  return SLUG_MAP[name] ?? SLUG_MAP[bare] ?? null;
}

function bucketFor(size: number): MomoSizeBucket {
  if (size <= 48) return "sm";
  if (size <= 96) return "md";
  return "lg";
}

export function MomoAvatar({
  agent,
  size = 40,
  sizeBucket,
  className,
}: {
  agent: MomoAvatarAgent;
  size?: number;
  sizeBucket?: MomoSizeBucket;
  className?: string;
}) {
  const [imgFailed, setImgFailed] = useState(false);
  const bucket = sizeBucket ?? bucketFor(size);
  const seed = `agent:${agent.name}`;
  const slug = slugFor(agent.name);
  const label = agent.display_name ?? agent.name;
  const accessibleName = agent.description
    ? `${label}, ${agent.description}`
    : label;
  const showImage = slug !== null && AVAILABLE_MOMO_SLUGS.has(slug) && !imgFailed;

  return (
    <span
      className={[styles.avatar, className].filter(Boolean).join(" ")}
      data-size={bucket}
      role="img"
      aria-label={accessibleName}
    >
      {showImage ? (
        <img
          className={styles.art}
          src={`/momentum/momos/${slug}.svg`}
          alt=""
          aria-hidden="true"
          width={size}
          height={size}
          onError={() => setImgFailed(true)}
        />
      ) : (
        <MomentumGlyph
          seed={seed}
          size={size}
          initial={label}
          className={styles.art}
        />
      )}
    </span>
  );
}
