"""Small fictional datasets for recipe previews; never substitute these for user facts."""

_EXAMPLES = {
    "offer": "Fictional Cedar Demo Studio offers a one-page website clarity review. The review is a draft report; no promised traffic or revenue increase.",
    "audience": "Owners of fictional neighborhood coffee shops who need clear service information on their existing websites.",
    "keyword_themes": "website review, coffee shop website help, local service page copy; search volumes are unavailable.",
    "service_catalog": "Website clarity review and service-page copy drafts; no ad management or platform migration in scope.",
    "search_terms": "coffee shop website review; website templates free; local website copy help; web development careers.",
    "target_region": "Fictional Cedar County. No other geography is confirmed.",
    "term_performance": "SYNTHETIC rows for one matched 7-day window: website review,12 clicks,2 qualified inquiries; free templates,18 clicks,0 recorded inquiries. Spend and untracked inquiries are unavailable.",
    "qualification_rules": "A qualified inquiry explicitly requests a website review and identifies a business; job inquiries and template downloads are not qualified.",
    "qualification_notes": "Fictional prospect requested a draft website review; timing and budget are unconfirmed. No promise was made.",
    "qualified_lead_definition": "An inquiry requesting a website clarity review for an existing business website.",
    "conversion_actions": "lead_form_received and booked_review_call; actions are supplied for draft mapping only.",
    "funnel_steps": "Visitor reads review offer, opens inquiry form, submits inquiry, optionally books a review call.",
    "event_inventory": "page_view, form_open, lead_form_received. booked_review_call has no verified event yet.",
    "attribution_requirements": "Distinguish form submissions from qualified inquiries; preserve unknown source attribution.",
    "hypothesis": "A clearer explanation of the review deliverable may improve qualified inquiry rate; this is an untested hypothesis.",
    "success_criteria": "Compare qualified inquiries per recorded visit using matched windows; stop if required tracking is missing. No spending is authorized by this fixture.",
    "creative_assets": "Owned synthetic photo of a blank notebook and an original Cedar Demo Studio wordmark. No third-party logo or testimonial.",
    "product_facts": "Deliverable is a written website clarity review with suggested copy. It does not include implementation.",
    "approved_claims": "Only claim a written clarity review and draft copy suggestions. No guaranteed lead, ranking or revenue result.",
    "offer_terms": "Draft website review; implementation, advertising changes and publishing require a separate agreement.",
    "offer_details": "A written review of one existing service page, three copy suggestions and an explicit evidence-gap list.",
    "ad_copy": "Make your website offer easier to understand. Request a written clarity review from Cedar Demo Studio.",
    "landing_copy": "Cedar Demo Studio writes service-page copy drafts. Contact us about a review; response time is unconfirmed.",
    "conversion_goal": "Prepare a useful inquiry about the written review; no real form submission.",
    "page_inventory": "Home:/; Review:/review; About:/about. The synthetic Review page explains a written clarity assessment.",
    "page_catalog": "Home:https://example.com/; Review:https://example.com/review; About:https://example.com/about.",
    "priority_pages": "Review:/review, then Home:/; no other page priority is confirmed.",
    "priority_urls": "https://example.com/review is the proposed primary review-offer page; priority is fictional.",
    "page_outline": "H1 Website clarity review; H2 What you receive; H2 What is outside scope; H2 How to request a review.",
    "reader_questions": "What will I receive? Who is this for? Does the service include publishing changes?",
    "customer_questions": "Does the review include implementation? Is a traffic increase guaranteed? What source material is required?",
    "current_answers": "Implementation is outside scope. No traffic increase is guaranteed. Supply the existing page and confirmed offer details.",
    "verified_answers": "A written clarity review provides draft suggestions. It does not include implementation or guarantee traffic.",
    "source_notes": "Synthetic source note1: signed fixture scope promises one written review. Note2: a fictional offer page excludes implementation.",
    "source_evidence": "Synthetic approved scope: one written review and three copy suggestions, with no guaranteed business result.",
    "draft_copy": "Synthetic draft says a website review will double inquiries; approved evidence provides no such guarantee.",
    "claim_policy": "Remove guarantees unsupported by approved evidence; identify claims needing proof before any publication.",
    "business_goals": "Prepare useful review drafts and explain the confirmed service clearly; measured growth targets are unavailable.",
    "topics": "Website offer clarity, useful service-page proof and honest contact expectations.",
    "publishing_constraints": "Two proposed posts per week; all publishing requires owner review. No deadline is approved.",
    "approved_updates": "A fictional written clarity-review service is available for draft inquiries; implementation remains outside scope.",
    "signature_text": "Cedar Demo Studio\nSynthetic demonstration sender\nhttps://example.com/",
    "approved_pitch": "We can prepare a written website clarity review and three specific copy suggestions; no result guarantee.",
    "verified_business_facts": "Fictional Cedar Coffee has one existing service page and an owner-supplied concern about confusing contact information.",
    "signed_scope": "Synthetic signed fixture: one written page review and three copy suggestions. No ads, publishing or website changes.",
    "agreed_scope": "One draft review of the existing service page, three copy suggestions and a proof-gap list.",
    "approved_terms": "Synthetic fixture fee is100 units; payment method and due date are unconfirmed. Do not send or bill.",
    "required_access": "Owner supplies public page text and approved offer facts. No password or account login is required.",
    "registry_records": "SYNTHETIC registry: cedar-demo-001=Cedar Coffee; cedar-demo-002=Cedar Community Books. These are distinct fictional businesses.",
    "incoming_references": "Cedar Coffee review request; Cedar Books event note; ambiguous reference Cedar requires clarification.",
    "matching_rules": "Exact canonical ID wins; a similar name alone is insufficient; ambiguous matches need human review.",
    "meeting_notes": "Synthetic meeting: Casey will draft the review; Morgan will confirm offer facts. No due date was agreed.",
    "confirmed_owners": "Casey owns the draft; Morgan owns offer-fact confirmation; no other assignment is approved.",
    "agreed_dates": "No due date was agreed; retain this as an unresolved scheduling input.",
    "verified_work_status": "Draft is prepared locally; owner review and delivery readback have not occurred.",
    "approved_work_records": "A synthetic fixture records one completed written review and three copy suggestions; no invoice has been issued.",
    "metric_export": "Synthetic matched weeks: prior120 visits and3 recorded inquiries; current140 visits and4 recorded inquiries. Revenue and missing tracking are unavailable.",
    "channel_exports": "Synthetic organic channel:140 visits,4 recorded inquiries; paid channel data unavailable. Both refer to the same fixture week.",
    "lead_records": "Synthetic leadA requests a written review; leadB asks about a job; leadC has no confirmed business need.",
    "time_series": "Synthetic daily visits:20,18,23,19,21,17,22. Prior comparison window and causal explanation are unavailable.",
    "measured_metrics": "Synthetic recorded page load4.2 seconds on a stated fixture device; image payload1.8MB. No field percentile or post-change measurement.",
    "source_excerpt": "Synthetic Python: def format_label(value): return value.strip(); an inputNone currently raises AttributeError.",
    "desired_behavior": "Return an empty label for None; preserve trimming for valid strings; do not change other input types silently.",
    "observed_behavior": "Synthetic fixture: format_label(None) raises AttributeError before the view can render.",
    "expected_behavior": "None produces an empty label and a string still has surrounding whitespace removed.",
    "test_results": "Synthetic fixture checks only: valid strings trim correctly; None regression is not fixed. No real test suite was run.",
    "chapter_text": "Synthetic original fiction: Mara returns a brass key to Ivo before crossing the river; in the final paragraph she opens a chest with that same key.",
    "continuity_notes": "Original fictional canon: Mara has only one brass key. Ivo keeps it after the river meeting. No spare key exists.",
    "character_facts": "Mara is a cautious cartographer; Ivo is her trusted sibling. They have not learned who built the sealed chest.",
    "manuscript_excerpt": "Synthetic original prose: Mara counted the river stones twice. The missing fifth stone meant someone had crossed before dawn.",
    "author_voice": "Original fictional voice: concrete observations, restrained emotion and short sentences; preserve the author's meaning.",
    "editing_constraints": "Propose line edits only; preserve character names, point of view and established plot facts.",
    "scene_purpose": "Mara must decide whether to reveal the missing river stone to Ivo while preserving their trust.",
    "established_plot": "Mara returned her only key to Ivo. The chest remains sealed. A fifth river stone is missing.",
    "character_motivations": "Mara wants reliable evidence before accusing anyone; Ivo wants to protect the town from panic.",
    "character_history": "Mara formerly rushed to an incorrect accusation and now requires evidence before acting.",
    "planned_scenes": "Mara notices the missing stone, asks Ivo about the crossing, then chooses a private investigation.",
    "story_theme": "Trust becomes stronger when uncertainty is stated honestly.",
    "world_rules": "Original fictional rule: the chest opens only with Mara's single brass key; the river path normally has five marker stones.",
    "story_excerpts": "Mara gives Ivo the only key, then later a draft has Mara open the chest. No key return is written.",
    "known_exceptions": "No exception to the one-key rule is approved; suggest questions rather than new canon.",
    "song_theme": "An original song about choosing to continue after a difficult night without pretending the problem is solved.",
    "original_lyrics": "Original synthetic lines: I mark the dawn in pencil / Leave the door an inch ajar / Tomorrow has no answer / But I know where we are.",
    "arrangement_constraints": "Use owned acoustic guitar and a simple vocal arrangement; no samples or borrowed lyrics.",
    "original_song_sections": "Synthetic original demo:8-bar verse,8-bar chorus,8-bar verse,8-bar chorus; bridge not written.",
    "emotional_arc": "Move from uncertainty through a concrete small choice to a restrained hopeful ending.",
    "performance_constraints": "One singer and acoustic guitar; comfortable lower vocal register;3-minute proposed duration.",
    "release_facts": "Synthetic artist Cedar Signal has one original single; release date and distribution approval are unconfirmed.",
    "owned_assets": "Original single, original lyric sheet and owned notebook photograph; cover design is not approved.",
    "approved_schedule": "No external release date approved. Prepare sequencing and dependencies only.",
    "session_goals": "Record two original vocal takes and compare phrasing using owner listening notes.",
    "available_equipment": "Owner-supplied fixture: acoustic guitar, one microphone, headphones and a local audio workstation.",
    "production_notes": "Owner's synthetic listening note: second verse words are difficult to understand; no audio file was analyzed.",
    "approved_biography": "Synthetic artist Cedar Signal writes original songs about ordinary uncertainty; no label affiliation, awards or credits.",
    "music_description": "Original acoustic songs with restrained vocals and narrative lyrics, as described by the fictional owner.",
    "research_question": "What concrete evidence would distinguish a durable saved worker conversation from an in-memory warm process?",
    "source_excerpts": "Synthetic technical note: metadata survives process restart; transcript persistence must be verified separately.",
    "knowledge_context": "Personal learning note about agent lifecycle; no provider benchmark or private repository is supplied.",
    "reading_excerpts": "Synthetic original noteA describes checkpoint storage; noteB describes recovery leases. Both are authored fixture notes.",
    "learning_question": "How do persisted state and admission leases cooperate during restart?",
    "prior_notes": "A successful HTTP response alone proves transport, not accepted useful output.",
    "learning_goal": "Explain and test a restart-resumable local worker using synthetic data.",
    "current_skills": "Reads Python and writes basic asynchronous tests; checkpoint namespace behavior is unfamiliar.",
    "available_time": "Three30-minute learning sessions this week; no external enrollment or purchase.",
    "admin_task": "Draft a personal equipment inventory note from owner-supplied records; no submission.",
    "verified_records": "Synthetic owned equipment: acoustic guitar and one USB microphone; purchase dates are unknown.",
    "required_format": "A short draft paragraph followed by explicit missing-record questions.",
    "commitments": "Synthetic commitments: one30-minute learning session and one45-minute original songwriting session.",
    "available_windows": "Owner-supplied fictional windows: Tuesday18:00–19:00 and Thursday18:00–19:00; timezone must be confirmed.",
    "run_receipts": "Synthetic local fixture: one graph run completed, output schema passed, independent review pending; billing unavailable.",
    "accepted_outputs": "No output has accepted evidence yet; do not infer acceptance from the completed process.",
    "observed_failures": "Synthetic fixture: a browser session expired before final page evidence; no retry was performed.",
}


def example_field(name: str, *, title: str, category: str) -> str:
    value = "Fictional test data: variantA100 recorded visits/3 inquiries; variantB110 visits/4 inquiries. Sample is small; revenue is unavailable." if name == "test_results" and category == "reporting" else _EXAMPLES.get(name)
    if value is None:
        value = (
            f"Fictional {category.replace('_', ' ')} brief for {title}: the owner permits a reviewable draft using supplied facts only. "
            f"Relevant {name.replace('_', ' ')} must preserve the stated objective, distinguish missing proof, and retain owner approval before external actions."
        )
    return "SYNTHETIC: " + value
